# Generated by Django 6.0 on 2025-12-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('Birth_Year', models.CharField(max_length=50)),
                ('Death_Year', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Birth_City', models.CharField(max_length=50)),
                ('Birth_Country', models.CharField(max_length=50)),
                ('Death_City', models.CharField(max_length=50)),
                ('Death_Country', models.CharField(max_length=50)),
            ],
        ),
    ]
