# Generated by Django 6.0 on 2025-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Incident', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Type_of_Event', models.CharField(max_length=50)),
                ('Place_Name', models.CharField(max_length=50)),
                ('Impact', models.CharField(max_length=50)),
                ('Affected_Population', models.CharField(max_length=50)),
                ('Important_Person_Group_Responsible', models.CharField(max_length=50)),
                ('Outcome', models.CharField(max_length=50)),
            ],
        ),
    ]
